# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test1

pod 'AudioKit', '~> 4.6.4'

  target 'Test1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
